In [1]:
#even or odd program
num = float(input("enter the number="))  
if num%2 == 0:  
    print("Number is even")
else:
        print("number is odd")

enter the number=4
Number is even


In [ ]:
#grade program
marks = int(input("Enter the marks= "))
if marks > 85 and marks <= 100:  
    print("Congrats  you scored grade A ")  
elif marks > 60 and marks <= 85:  
    print("You scored grade B + ")  
elif marks > 40 and marks <= 60:  
    print("You scored grade B ")  
elif (marks > 30 and marks <= 40):  
    print("You scored grade C ")  
else:  
    print("Sorry you are fail ?")

In [4]:
a=(input("enter a string="))
print(a)

enter a string=shhgg
shhgg


In [2]:
#reverse a string
a=(input("enter a string to reverse="))
print(a[::-1])

enter a string to reverse=shakti
itkahs


In [3]:
#check palindrom or not
a = input("Please enter a String : ")

if(a == a[:: - 1]):
   print("This is a Palindrome String")
else:
   print("This is Not a Palindrome String")

Please enter a String : cuttuc
This is a Palindrome String


In [7]:
#print natural numbers
i=1  
n=int(input("Enter a number="))  
for i in range(1,n):  
    print(i)  

Enter a number=12
1
2
3
4
5
6
7
8
9
10
11


In [8]:
#print natural number in reverse order
i=1  
n=int(input("Enter a number=")) 
for i in range(n,-1,-1):
    print(i)

Enter a number=2
2
1
0


In [9]:
#copy one list elements into other
a=[1,2,3,4,5]
b=[]
for i in a:
    b.append(i)
print(b)

    

[1, 2, 3, 4, 5]


In [10]:

for i in range(1,11):
    print(i)
print(i)

1
2
3
4
5
6
7
8
9
10
10


In [11]:
a=[1,2,3,4,5]
sum=0
for i in a:
    sum=sum+i
print(sum)
    

15


In [19]:
#check prime number or not
num = int(input("Enter a number: "))
c=0
for i in range(1,num+1):
    if (num % i == 0):
            c=c+1
if(c==2):
      print(num,"is  a prime number")
else:
    print(num,"is not  a prime number")  

Enter a number: 5
5 is  a prime number


In [3]:
#fibonacci series
n=int(input('enter a number='))
a=0
b=1

print(a,b)
for i in range(0,n):
    
    i=a+b
    a=b
    b=i    
    print(i)


enter a number=5
0 1
1
2
3
5
8


In [14]:
# use of [.format] function
s="shakti"
i=5
print("string is {s} int is {i}".format(s=s,i=i))

string is shakti int is 5


In [1]:
#multiplication table program
num = int(input("Show the multiplication table of? ")) 
for i in range(1,11):  
    print(num,'x',i,'=',num*i) 

Show the multiplication table of? 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [1]:
#birthday reminder app
dict={}
while True:
    print("------------Birthday App---------------")
    print("1.show birthday")
    print("2.Add Birthday")
    print("3.Exit")
    choice=int(input("enter the choice"))
    if choice ==1:
        if len(dict.keys())==0:
            print("No record Found")
        else:
            name=input("enter your friends name")
            birthday=dict.get(name,"no data found")
            print(birthday)
    elif choice==2:
            name=input("enter your friends name=")
            date=input("enter birthday=")
            dict[name]=date
            print("Birthday Addded")
    elif choice==3:
            break
    else:
            print("choice a valid option")
            
        

------------Birthday App---------------
1.show birthday
2.Add Birthday
3.Exit
enter the choice3


In [11]:
#use of function
def shakti():
    return "some"
    print("fidbudsyfb")
a=shakti()
print(a)

some


In [5]:
#armstrong number
a=int(input("enter a no="))
num=a
rem=0
sum=0
while(num>0):
    rem=num%10
    rem=pow(rem,3)
    num=int(num/10)
    sum=sum+rem
if(sum==a):
    print("armstrong no")
else:
    print("not a armstrong num")
    


enter a no153
armstrong no


In [12]:
def farin(a,b):
    c=a+b
    return 0
z=farin(5,3)
print(z)


8
0


In [2]:
print("{s} something  {v}".format(s=5,v=10))



5 something  10


In [1]:
#find factorial of a number
a=int(input("Enter a number"))
i=1
fact=1
while(i<=a):
    fact=fact*i
    i=i+1
print("Factorial of the given no is {one}".format(one=fact))

Enter a number5
Factorial of the given no is 120


In [3]:
import numpy as np

In [18]:
np.ones(4)


array([1., 1., 1., 1.])

In [19]:
np.zeros(4)

array([0., 0., 0., 0.])

In [20]:
range(5)

range(0, 5)

In [26]:
a=np.reshape(a,newshape=[5,5])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
import pandas as pd


In [8]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
import pandas as pd
import numpy as np

NameError: name 'pd' is not defined

In [20]:
a=np.arange(36)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [21]:
a=np.reshape(a,[6,6])
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [2]:
import pandas as pd
import numpy as np
x=[]
y=[]
a=np.arange(36)
a=np.reshape(a,[6,6])

for i in range(6):
    n=int(input("enter marks= "))
    x.append(n)
    p=input("enter student name=")
    y.append(p)

df=pd.DataFrame(a,index=x,columns=y)
print(df)
    

enter marks= 54
enter student name=shkti
enter marks= 86
enter student name=ruuu
enter marks= 97
enter student name=gdhbuaib
enter marks= 46
enter student name=ekhfbc
enter marks= 55
enter student name=ksbkcs 
enter marks= 77
enter student name=wadb
    shkti  ruuu  gdhbuaib  ekhfbc  ksbkcs   wadb
54      0     1         2       3        4     5
86      6     7         8       9       10    11
97     12    13        14      15       16    17
46     18    19        20      21       22    23
55     24    25        26      27       28    29
77     30    31        32      33       34    35


5
['e', 'e', 'o', 'e', 'e']
